version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organica
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    volumes:
    - ./init:/docker-entrypoint-initdb.d



  backend:
    build:
      context: ./server/Dockerfile
      dockerfile: ./server/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ecomdatabase.cbkeww6w0vg0.ap-southeast-2.rds.amazonaws.com
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password519436
    
    ports:
      - 9090:9090
    depends_on:
      - mysql
    

  frontend:
    build:
      context: ./client/Dockerfile
      dockerfile: ./client/Dockerfile
    ports:
      - 3000:3000
